"""empty message

Revision ID: e3803833815f
Revises: 
Create Date: 2026-02-25 18:49:33.350581

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e3803833815f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apellidos', sa.String(length=120), nullable=True))
        batch_op.alter_column('telefono',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.drop_column('apaterno')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apaterno', mysql.VARCHAR(length=50), nullable=True))
        batch_op.alter_column('telefono',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=True)
        batch_op.drop_column('apellidos')

    # ### end Alembic commands ###
